
server:
  port: 8081
spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;database=newfolder;encrypt=true;trustServerCertificate=true
        username: sa
        password: 12341234
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      hibernate:
        ddl-auto: update

      show-sql: true
      properties:
        hibernate:
          dialect:





jwt:
  secretKey: "mySuperSecretKeyForJwt123456789987654321"
  expiration: 4000000
  refreshKey : "Y3N5eHN5Y3N5eHN4Z3J0eHh5Y2V2eWNleXZ5Y2d4Z3VseG5sY3N0"
  expirationDate : 2500000000